import type { Metadata } from "next";
import { MODEL_CONFIG, SOURCES } from "@/lib/config";

export const metadata: Metadata = { title: "Moonbow Model Methodology", description: "Transparent methodology for Cumberland Falls Moonbow Live: physical gates, estimated chance, multi-model weather, river mist, confidence and calibration policy.", robots: { index: true, follow: true }, alternates: { canonical: "/cumberland-falls-moonbow/methodology" } };

export default function Methodology() { return <main className="content-page shell" id="main"><p className="content-page__eyebrow">{MODEL_CONFIG.id} · version {MODEL_CONFIG.version}</p><h1>How the moonbow decision works</h1><p className="lede">The tool starts with physics, then asks how much useful moonlight and mist are likely to exist during the geometrically valid window. The public Estimated Moonbow Chance is intentionally coarse and is not yet an empirically calibrated success frequency.</p>
  <h2>Hard gates first</h2><p>A five-minute interval is not viable if the Moon is below the effective skyline, above 42°, the Sun is above −12°, lunar illumination is below the validated planning envelope, the primary 40–42° bow geometry misses the modeled mist field, astronomy is invalid, direct moonlight is effectively blocked, or a dangerous NWS alert applies. Weather and river flow cannot compensate for impossible optics.</p>
  <h2>Seven factors, multiplied</h2><p><code>S = 100 × L^0.18 × G^0.24 × C^0.24 × M^0.14 × P^0.08 × A^0.07 × W^0.05</code></p><p>L is effective lunar light, G bow/mist geometry, C cloud transmission, M mist production, P wind-driven mist placement, A atmospheric clarity, and W excessive-wind penalty. The multiplicative form prevents a weak critical ingredient from being hidden by high unrelated scores.</p>
  <h2>Local geometry</h2><p>Moon and Sun positions are computed locally with <a href={SOURCES.astronomy.url}>Astronomy Engine</a> and checked against JPL Horizons fixtures. The bare-earth skyline is sampled from <a href={SOURCES.terrain.url}>USGS 3DEP</a>, with a separate conservative tree-line correction. The engine projects the antilunar geometry against a modeled Cumberland Falls mist volume rather than treating Moon altitude as a generic score.</p>
  <h2>Weather: official forecast plus model consensus</h2><p>The NWS JKL digital forecast remains the official forecast and alert source. A separate consensus compares NOAA HRRR, NOAA NBM, NOAA GFS and ECMWF IFS guidance through <a href={SOURCES.openMeteo.url}>Open-Meteo</a>. Low cloud receives the strongest optical penalty, mid cloud a strong penalty, and high cloud a smaller penalty. Model spread lowers confidence. Inside three hours, recent surface observations and NOAA GOES-19 cloud information gain additional weight.</p>
  <h2>River flow and mist</h2><p>River discharge and gage height come from modern USGS Water Data services for station 03404500. A 1991–2025 daily-flow distribution supplies seasonal context. Mist production rises quickly with flow and then saturates; exceptional flood flow receives only a small conservative overspray penalty because a precise high-flow optimum has not been established. Wind direction is modeled separately as mist placement because the useful question is whether spray remains in the optical viewing zone.</p>
  <h2>Estimated chance and confidence are different</h2><p>The physical Moonbow Score is converted to an Estimated Moonbow Chance only when date-specific weather evidence exists. The estimate is rounded to five-point increments and capped by evidence quality. Beyond the date-specific forecast horizon it is withheld rather than fabricating precision. Confidence separately reflects forecast lead time, source freshness, missing data and model agreement.</p>
  <h2>Calibration path</h2><p>Visitor reports store the issued forecast variables and observed outcome. Once there is a sufficiently large time-separated dataset, the estimated chance can be calibrated and evaluated with Brier score, reliability curves, false-positive rate and false-negative rate. Until that validation exists, the percentage should be read as a model estimate, not “84 of 100 identical nights.”</p></main>; }
