import type { Metadata } from "next";
import { MODEL_CONFIG, SOURCES } from "@/lib/config";

export const metadata: Metadata = { title: "Moonbow Model Methodology", description: "Transparent methodology for the Cumberland Falls Moonbow Score, hard physical gates, data freshness, confidence and calibration policy.", robots: { index: true, follow: true }, alternates: { canonical: "/cumberland-falls-moonbow/methodology" } };

export default function Methodology() { return <main className="content-page shell" id="main"><p className="content-page__eyebrow">Model version {MODEL_CONFIG.version}</p><h1>How the decision works</h1><p className="lede">The Moonbow Score is a transparent, multiplicative opportunity index. It is deliberately not labeled a probability.</p>
  <h2>Hard gates first</h2><p>A timestep receives no viable score if the Moon is below the effective skyline, above 42°, the Sun is above −12°, lunar illumination is below 88%, the primary bow misses the modeled mist field, astronomy is invalid, clouds fully block direct moonlight, or a dangerous NWS alert applies.</p>
  <h2>Six factors, multiplied</h2><p><code>S = 100 × L^0.20 × G^0.25 × C^0.25 × M^0.15 × A^0.08 × W^0.07</code></p><p>L is lunar brightness, G bow/mist geometry, C cloud transmission, M the saturating flow-to-mist proxy, A atmospheric clarity, and W a deliberately low-weight wind term. A low critical factor cannot be hidden by high unrelated factors.</p>
  <h2>Local geometry</h2><p>Moon and Sun positions are computed locally with <a href={SOURCES.astronomy.url}>Astronomy Engine</a>, whose test suite is compared with JPL Horizons. The bare-earth horizon is sampled from <a href={SOURCES.terrain.url}>USGS 3DEP</a>. A separate, visible tree-line correction is added; visitor reports will refine it.</p>
  <h2>Weather and river data</h2><p>The date-specific forecast comes from the NWS JKL grid. Inside three hours, recent surface observations and NOAA GOES-19’s 2 km Clear Sky Mask join the cloud estimate. River discharge and gage height come from modern USGS Water Data APIs for station 03404500; a 1991–2025 daily-flow distribution supplies seasonal context.</p>
  <h2>Confidence is not opportunity</h2><p>Confidence starts from forecast horizon and falls when a source is missing or stale. Beyond seven days, weather is explicitly marked climatology/planning; it never masquerades as a forecast. Drive commitment changes recommendation thresholds, never the physical score.</p>
  <h2>When “probability” may appear</h2><p>Only after time-separated holdout validation beats near-full-Moon, Moon-plus-clear-forecast, and official-calendar-plus-weather baselines, with Brier score ≤0.18 and expected calibration error ≤0.10. Until then, 84/100 means score—not an 84% chance.</p></main>; }
